### PR TITLE
to save your personal data

### PR DESCRIPTION
**Pull request by DancerVlt69**
Read the Git-Commits and the Comments in the changed / added file

But hey, make the changes only if you want! 

If you have any questions feel free to ask on  Discord

### CODE REVIEW

**Comment by DomakingTheKing** [comment]
Thx, appreciate it ^-^

**Comment by DancerVlt69** [comment]
One request: I've forget to add the credits in the coloredConsole.gradle - that's not my code!

please can you add the following 4 lines on the top of the file? Thanks

// Credits
// Author: Nishant Srivastava
// Web: https://crushingcode.nisrulz.com/posts/rainbow-console-logs-in-groovy/
// GitHub: https://github.com/nisrulz/android-examples/tree/develop/ColoredConsoleLogs

**Comment by DomakingTheKing** [comment]
Done, thx ^_^

Il giorno gio 12 gen 2023 alle ore 21:20 DancerVLT69 <
***@***.***> ha scritto:

**Comment by DancerVlt69** [comment]
Thank you

**Pull request merged**
